### PR TITLE
function to facilitate production of dataframe for image paths and labels from file names!

### PR DESCRIPTION
**Pull request by kareemelfatairy**
```

def filename_to_class (*filelist,classes:list):
    ''' purpose: Create dataframe of file pathes and labels extracted from file name.
        Argument:
        *filelist: returns list of paths.
        classes: a list of desired classes as seen in file name.
    
    '''
    
        file_list = map(datautils.list_of_files,filelist)  #get a list of files from folders
        
        data={'image_path':[],'image_label':[]}     

       


        for i in file_list:  
          for z in i:          #create lists of files with the specified label and append to the dictionary
            for _,item in enumerate(classes):
              #print(item)
              if item.casefold() in z.casefold():   #case insensitive match
                data['image_path'].append(i)
                data['image_label'].append(item)
    
        df=pd.DataFrame(data)
    return df

```

### CODE REVIEW

**Comment by elbanan** [comment]
What about this :

```
def filename_to_class (directory,classes):
  file_list = datautils.list_of_files(directory)
  files = []
  labels = []
  for i in file_list:
    for item in classes:
      if item.casefold() in i.casefold():
        files.append(i)
        labels.append(item)
  output = pd.DataFrame(list(zip(files, labels)), columns=['IMAGE_PATH', 'IMAGE_LABEL'])     
  return output
```

**Comment by kareemelfatairy** [comment]
ok,

so I am not sure how did this solve the complexity but I will tell you why I wrote the code this way

regarding the function parameters (*filelist,classes:list):
--when we take your example, data were in two folders, (pneumonia and normal). this means 2 paths correct?
in your function you will not be able to fit 2 paths as argument.
*filelist can do this--returning a list of paths
for classes:list-->this enforces that this argument take ONLY list datatype.

I am sure you know what map function does.
then I make a dictionary with the data columns as keys and file lists as values. and finally passing it to DataFrame object.
I agree, there is no rational for using enumerate in the classes loop ( this is dump :))

hope this demystifies my code rationale

**Comment by elbanan** [comment]
Oh got it, then your code is perfect. My only concern is that the file paths returned in the first column of pd are lists. We need it to be strings.

**Comment by elbanan** [comment]
@kareemelfatairy: btw, I checked the code again. I am getting all files in all rows of the dataframe. it is not just a single path.

**Comment by kareemelfatairy** [comment]
Alsta?!! 👍

**Comment by elbanan** [comment]
@kareemelfatairy alesta 😃 I will close this request and add the code to v0.1.4 branch. I will rename it to (datatable_from_filepath). what do you think?

**Comment by kareemelfatairy** [comment]
sounds great!
thanks for accepting my pull request.
Baby steps for me :D

**Comment by elbanan** [comment]
> sounds great!
> thanks for accepting my pull request.
> Baby steps for me :D

No man you are doing great !!! btw, for future work, put your new code in  the v0.1.4 branch then we can discuss it in the @radtorch/radtorch-dev . I think it will be better there.

**Comment by kareemelfatairy** [comment]
ok

**Pull request closed without merging**
